name: PR Title Check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Danger globally
        run: npm install -g danger

      - name: Run Danger
        run: danger ci --dangerfile=./.github/.dangerfile.ts
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
